# Copyright (c) 2025-2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import numpy as np
from dataclasses import dataclass
from typing import Any

from openpi_client import image_tools

from isaaclab_arena_openpi.policy.pi0_remote_policy import Pi0EmbodimentAdapter


@dataclass(frozen=True)
class PiperObservation:
    """Per-env tensors needed to assemble an openpi AgileX-style request for double Piper."""

    cam_top_image: np.ndarray  # (H, W, 3) uint8 — overhead / first-person camera
    cam_left_wrist_image: np.ndarray  # (H, W, 3) uint8
    cam_right_wrist_image: np.ndarray  # (H, W, 3) uint8
    left_joint_position: np.ndarray  # (6,) float32
    right_joint_position: np.ndarray  # (6,) float32
    left_gripper_position: np.ndarray  # (1,) float32
    right_gripper_position: np.ndarray  # (1,) float32


class Pi0PiperAdapter(Pi0EmbodimentAdapter):
    """Wire format for openpi AgileX/Piper checkpoints applied to double Piper.

    Input wire format (matching AgileXInputs):
      - state: [left_arm(6), right_arm(6)] = 12 dims
      - gripper_position: [left_gripper(1), right_gripper(1)] = 2 dims
      - images: cam_top, cam_left_wrist, cam_right_wrist

    Output wire format (matching AgileXOutputs):
      - actions: [left_arm(6), left_gripper(1), right_arm(6), right_gripper(1)] = 14 dims
      - gripper values are percentage (0~100)
    """

    # Server returns 14 dims: [left_arm(6), left_gripper(1), right_arm(6), right_gripper(1)]
    action_dim = 14

    open_loop_horizon_by_variant = {
        "pi05": 50,
        "pi0": 10,
    }

    target_image_size = (224, 224)

    # Arena observation group keys
    arena_camera_obs_group = "camera_obs"
    arena_policy_obs_group = "policy"

    # Camera keys as generated by make_camera_observation_cfg from DoublePiperCameraCfg
    arena_first_person_camera_key = "first_person_camera_rgb"
    arena_left_hand_camera_key = "left_hand_camera_rgb"
    arena_right_hand_camera_key = "right_hand_camera_rgb"

    # Gripper joint limits for normalization
    # Piper gripper: open=0.035, close=0.0
    gripper_open = 0.035

    def extract(self, observation: dict[str, Any], env_id: int) -> PiperObservation:
        cam = observation[self.arena_camera_obs_group]
        proprio = observation[self.arena_policy_obs_group]

        # Gripper: average the two finger joints and normalize to [0, 1] fraction
        left_gripper_raw = proprio["left_gripper_pos"][env_id].detach().cpu().numpy()
        right_gripper_raw = proprio["right_gripper_pos"][env_id].detach().cpu().numpy()

        # finger_joint_left and finger_joint_right are symmetric (one positive, one negative)
        # Take the mean of absolute values
        left_gripper_norm = np.clip(np.abs(left_gripper_raw).mean() / self.gripper_open, 0.0, 1.0)
        right_gripper_norm = np.clip(np.abs(right_gripper_raw).mean() / self.gripper_open, 0.0, 1.0)

        return PiperObservation(
            cam_top_image=cam[self.arena_first_person_camera_key][env_id].detach().cpu().numpy(),
            cam_left_wrist_image=cam[self.arena_left_hand_camera_key][env_id].detach().cpu().numpy(),
            cam_right_wrist_image=cam[self.arena_right_hand_camera_key][env_id].detach().cpu().numpy(),
            left_joint_position=proprio["left_joint_pos"][env_id].detach().cpu().numpy(),
            right_joint_position=proprio["right_joint_pos"][env_id].detach().cpu().numpy(),
            left_gripper_position=np.array([left_gripper_norm], dtype=np.float32),
            right_gripper_position=np.array([right_gripper_norm], dtype=np.float32),
        )

    def pack_request(self, extracted: PiperObservation, language_instruction: str) -> dict[str, Any]:
        target_height, target_width = self.target_image_size

        # state: [left_arm(6), right_arm(6)] — gripper sent separately
        state = np.concatenate([
            extracted.left_joint_position,
            extracted.right_joint_position,
        ]).astype(np.float32)

        # gripper_position: [left_gripper(1), right_gripper(1)]
        gripper_position = np.concatenate([
            extracted.left_gripper_position,
            extracted.right_gripper_position,
        ]).astype(np.float32)

        # print(f"[PiperAdapter] state shape: {state.shape}, values: {state}")
        # print(f"[PiperAdapter] gripper_position shape: {gripper_position.shape}, values: {gripper_position}")
        print(f"[PiperAdapter] current left_arm: {extracted.left_joint_position}")
        print(f"[PiperAdapter] current right_arm: {extracted.right_joint_position}")
        # print(f"[PiperAdapter] cam_top shape: {extracted.cam_top_image.shape}, dtype: {extracted.cam_top_image.dtype}")
        # print(f"[PiperAdapter] cam_left_wrist shape: {extracted.cam_left_wrist_image.shape}")
        # print(f"[PiperAdapter] cam_right_wrist shape: {extracted.cam_right_wrist_image.shape}")

        def _to_chw(img: np.ndarray) -> np.ndarray:
            # resize_with_pad returns HWC (H, W, 3); server expects CHW (3, H, W)
            return np.transpose(image_tools.resize_with_pad(img, target_height, target_width), (2, 0, 1))

        return {
            "state": state,
            "gripper_position": gripper_position,
            "images": {
                "cam_top": _to_chw(extracted.cam_top_image),
                "cam_left_wrist": _to_chw(extracted.cam_left_wrist_image),
                "cam_right_wrist": _to_chw(extracted.cam_right_wrist_image),
            },
            "prompt": language_instruction,
        }

    def unpack_actions(self, actions: np.ndarray) -> np.ndarray:
        """Convert server output to Arena action format.

        Server returns: [left_arm(6), left_gripper(1), right_arm(6), right_gripper(1)]
          - gripper values are percentage (0~100)

        Arena expects:  [left_arm(6), right_arm(6), left_gripper(1), right_gripper(1)]
          - gripper is binary command (BinaryJointPositionAction: 1.0=open, 0.0=close)
        """
        print(f"[PiperAdapter] raw actions from server shape: {actions.shape}")
        print(f"[PiperAdapter] raw actions[0]: {actions[0]}")
        print(f"[PiperAdapter] raw actions arm range: min={actions[:, :6].min():.4f}, max={actions[:, :6].max():.4f}")

        left_arm = actions[:, :6]
        left_grip_pct = actions[:, 6:7]  # percentage 0~100
        right_arm = actions[:, 7:13]
        right_grip_pct = actions[:, 13:14]  # percentage 0~100

        # BinaryJointPositionZeroToOneAction: 0.0 = OPEN, 1.0 = CLOSE
        # AgileX server: large gripper value = OPEN, small value = CLOSE
        # Note: server does NOT apply _encode_actions (commented out), so output is raw [0,1]
        left_grip_cmd = (left_grip_pct <= 0.5).astype(np.float32)
        right_grip_cmd = (right_grip_pct <= 0.5).astype(np.float32)

        return np.concatenate([left_arm, right_arm, left_grip_cmd, right_grip_cmd], axis=1)
